name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change to master if you're using the master branch
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          
      # Optionally, add a step to invalidate Vercel cache (if needed)
      # - name: Invalidate Vercel cache
      #   run: |
      #     curl -X POST -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
      #     https://api.vercel.com/v2/integrations/deploy/prj_<project_id>/invalidate_cache
